; bed.g
; called to level the bed
;
; generated by RepRapFirmware Configuration Tool v3.5.10 on Wed Mar 26 2025 13:55:02 GMT-0500 (hora estándar de Colombia)

G31 X0 Y0 Z0
G29 ; call mesh bed compensation
