; homeall.g
; called to home all axes
;
; generated by RepRapFirmware Configuration Tool v3.5.10 on Wed Mar 26 2025 13:55:08 GMT-0500 (hora estándar de Colombia)

; increase Z
G91 ; relative positioning
G1 H2 Z4 F6000 ; move Z relative to current position to avoid dragging nozzle over the bed
G90 ; absolute positioning

; home XY
var xTravel = move.axes[0].max - move.axes[0].min + 5 ; calculate how far X can travel plus 5mm
var yTravel = move.axes[1].max - move.axes[1].min + 5 ; calculate how far Y can travel plus 5mm
G91 ; relative positioning
G1 H1 X{-var.xTravel} Y{-var.yTravel} F1100 ; coarse home
G1 H1 X{-var.xTravel} F1100 ; coarse home in the -X direction
G1 H1 Y{-var.yTravel} F1100 ; coarse home in the -Y direction
G1 X5 Y5 F8000 ; move back 5mm
G1 H1 X{-var.xTravel} Y{-var.yTravel} F300 ; fine home
G1 H1 X{-var.xTravel} F300 ; fine home in the -X direction
G1 H1 Y{-var.yTravel} F300 ; fine home in the -Y direction
G1 X5 Y5 F8000 ; move back 5mm
G90 ; absolute positioning

; home Z
var zTravel = move.axes[2].max - move.axes[2].min + 5 ; calculate how far Z can travel plus 5mm
G91 ; relative positioning
G1 H1 Z{-var.zTravel} F900 ; coarse home in the -Z direction
G1 H2 Z5 ;F6000 ; move back 5mm
G1 H1 Z-5 F300 ; fine home in the -Z direction
G1 H2 Z5 F6000 ; move back 5mm
G1 X140.5 Y190.5 F6000 ; move to the center
G1 H2 Z-3.9 F300 ; move near to the nozzel
G92 X0 Y0 Z0
G90 ; absolute positioning


