; homey.g
; called to home the Y axis
;
; generated by RepRapFirmware Configuration Tool v3.5.10 on Wed Mar 26 2025 13:55:08 GMT-0500 (hora estándar de Colombia)

; home Y
G91 ; relative positioning
G1 H2 Z3 F8000    ; lift Z relative to current position
var maxTravel = move.axes[1].max - move.axes[1].min + 5 ; calculate how far Y can travel plus 5mm
G1 H1 Y{-var.maxTravel} F1100 ; coarse home in the -Y direction
G1 Y5 F8000 ; move back 5mm
G1 H1 Y{-var.maxTravel} F300 ; fine home in the -Y direction
G1 Y190.5 F8000 ; move back 5mm
G92 Y0 
G90 ; absolute positioning

