; homez.g
; called to home the Z axis
;
; generated by RepRapFirmware Configuration Tool v3.5.8 on Thu Nov 28 2024 16:22:02 GMT-0500 (Colombia Standard Time)

; Asegurar que XY estén homed
M98 P"homex.g"
M98 P"homey.g"

; home Z
var zTravel = move.axes[2].max - move.axes[2].min + 5 ; calculate how far Z can travel plus 5mm
G91 ; relative positioning
G1 H1 Z{-var.zTravel} F1000 ; coarse home in the -Z direction
G1 H2 Z5 ;F8000 ; move back 5mm
G1 H1 Z-5 F300 ; fine home in the -Z direction
G1 H2 Z5 F8000 ; move back 5mm
G1 H2 Z-3.9 F300 ; move near to the nozzel
G92 Z0
G90 ; absolute positioning
