; homex.g
; called to home the X axis
;
; generated by RepRapFirmware Configuration Tool v3.5.10 on Wed Mar 26 2025 13:55:08 GMT-0500 (hora estándar de Colombia)


; home X
G91 ; relative positioning
G1 H2 Z3 F8000    ; lift Z relative to current position
var maxTravel = move.axes[0].max - move.axes[0].min + 5 ; calculate how far X can travel plus 5mm
G1 H1 X{-var.maxTravel} F1100 ; coarse home in the -X direction
G1 X5 F8000 ; move back 5mm
G1 H1 X{-var.maxTravel} F300 ; fine home in the -X direction
G1 X140.5 F8000G1 ; move back 
G92 X0 
G90 ; absolute positioning
